Repository openshift/cluster-etcd-operator, pull requests merged in 2019-02, with the labels that each got.

#2 *: update operator boilerplate to reflect proper naming
  Makefile
  README.md
Labels: size/XS

#5 Add manifests for installation
  manifests/0000_12_etcd-operator_00_namespace.yaml
  manifests/0000_12_etcd-operator_01_config.crd.yaml
  manifests/0000_12_etcd-operator_02_service.yaml
  manifests/0000_12_etcd-operator_03_configmap.yaml
  manifests/0000_12_etcd-operator_04_clusterrolebinding.yaml
  manifests/0000_12_etcd-operator_05_serviceaccount.yaml
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
  manifests/0000_90_etcd-operator_01_prometheusrole.yaml
  manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: size/L

#6 fix the operator config type
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/00_openshift-etcd-ns.yaml
  bindata/bootkube/manifests/configmap-initial-etcd-serving-ca.yaml
  bindata/bootkube/manifests/configmap-kube-controller-manager-client-ca.yaml
  bindata/bootkube/manifests/secret-cluster-signing-ca.yaml
  bindata/bootkube/manifests/secret-kubeconfig.yaml
  bindata/bootkube/manifests/secret-service-account-private-key.yaml
  bindata/v3.11.0/etcd/defaultconfig.yaml
  bindata/v3.11.0/etcd/operator-config.yaml
  pkg/cmd/render/testdata/configs/kube-controller-manager-config-overrides.yaml
  pkg/operator/v311_00_assets/bindata.go
Labels: approved, do-not-merge/hold, size/L
