Repository openshift/cluster-etcd-operator, pull requests merged in 2019-11, with the labels that each got.

#29 *: add ManagementState support to controllers
  Dockerfile
  Dockerfile.rhel7
  manifests/0000_12_etcd-operator_01_operator.cr.yaml
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/0000_12_etcd-operator_06_static_pod_demonset.yaml
  manifests/0000_12_etcd-operator_06_static_sync_demonset.yaml
  pkg/cmd/staticpodcontroller/staticpodcontroller.go
  pkg/cmd/staticsynccontroller/staticsynccontroller.go
  pkg/operator/bootstrapteardown/teardown.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go
  pkg/operator/starter.go
  pkg/operator/statuscontroller/condition.go
  pkg/operator/statuscontroller/statuscontroller.go
Labels: approved, lgtm, size/XL

#31 Dockerfile: remove from CVO operator payload
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#33 pkg/cmd/*: fix openshift operator clients and host-endpoint-controller
  pkg/cmd/staticpodcontroller/staticpodcontroller.go
  pkg/cmd/staticsynccontroller/staticsynccontroller.go
  pkg/operator/bootstrapteardown/teardown.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/configobservation/etcd/observe_etcd.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/L
