Repository openshift/cluster-etcd-operator, pull requests merged in 2019-07, with the labels that each got.

#14 OWNERS: add hexfusion
  OWNERS
  glide.lock
  glide.yaml
Labels: approved, lgtm, size/S

#15 pkg/cmd: add setup-etcd-environment
  Makefile
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/setupetcd/OWNERS
  pkg/cmd/setupetcd/setupetcd.go
  pkg/version/version.go
Labels: approved, lgtm, size/L

#17 Change bootstrap name to etcd-bootstrap to match DNS
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
Labels: approved, lgtm, size/XS
