Repository openshift/cluster-etcd-operator, pull requests merged in 2020-07, with the labels that each got.

#381 remove etcdMemberIPMigrator controller
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
  pkg/operator/starter.go
Labels: approved, lgtm

#386 Remove etcdDiscoveryDomain
  pkg/cmd/render/render.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, lgtm

#387 hack: add shellcheck
  hack/shellcheck.sh
Labels: approved, lgtm

#353 update the operator to create a complete etcd service
  bindata/etcd/svc.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#390 Bug 1847878: Reduce superfluous leader change logging
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#388 Bug 1846093: Make bootstrap IP discovery backwards compatible with previous assumptions
  pkg/cmd/render/bootstrap_ip.go
  pkg/cmd/render/bootstrap_ip_test.go
  pkg/cmd/render/render.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#395 Update OWNERS
  OWNERS
Labels: approved, lgtm

#393 Bug 1843863: Clean up EtcdLeaderChangeMetrics event description
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#400 Set ETCD_UNSUPPORTED_ARCH on arm64
  pkg/cmd/render/env.go
  pkg/cmd/render/env_test.go
  pkg/etcdenvvar/etcd_env.go
Labels: approved, lgtm

#399 vendor: bump etcd v3.4.9
  go.mod
  go.sum
  vendor/go.etcd.io/etcd/clientv3/balancer/picker/err.go
  vendor/go.etcd.io/etcd/clientv3/balancer/picker/roundrobin_balanced.go
  vendor/go.etcd.io/etcd/clientv3/balancer/resolver/endpoint/endpoint.go
  vendor/go.etcd.io/etcd/clientv3/maintenance.go
  vendor/go.etcd.io/etcd/etcdserver/etcdserverpb/rpc.pb.go
  vendor/go.etcd.io/etcd/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#394 Migrate etcd-quorum-guard from MCO.
  Makefile
  go.mod
  manifests/0000_12_etcd-operator_08_etcdquorumguard_deployment.yaml
  manifests/0000_12_etcd-operator_09_etcdquorumguard_pdb.yaml
  manifests/image-references
  test/e2e/etcquorumguard_test.go
  test/e2e/framework/clientset.go
  test/e2e/main_test.go
Labels: approved, lgtm

#409 manifests: add operand to co
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
Labels: approved, lgtm

#412 Render bootstrap certificates
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm
