Repository openshift/cluster-etcd-operator, pull requests merged in 2020-08, with the labels that each got.

#415 Converting cluster-backup and cluster-restore shell scripts as subcommands
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/backuprestore/backuprestore.go
  pkg/cmd/backuprestore/backuputils.go
  pkg/cmd/backuprestore/etcdclientutils.go
  pkg/cmd/backuprestore/fileioutils.go
  pkg/cmd/backuprestore/restoreutils.go
  pkg/cmd/backuprestore/tarutils.go
Labels: approved, lgtm

#416 Clean up bootstrap member cert references
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/render.go
Labels: approved, lgtm

#417 Use crioclient to verify all static pods have stopped ...
  go.mod
  go.sum
  pkg/cmd/backuprestore/backuprestore.go
  pkg/cmd/backuprestore/crioclient.go
  pkg/cmd/backuprestore/fileioutils.go
  pkg/cmd/backuprestore/restoreutils.go
  vendor/k8s.io/cri-api/LICENSE
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/constants.go
  vendor/modules.txt
Labels: approved, lgtm

#405 Document how etcd's TLS assets are managed
  docs/etcd-tls-assets.md
Labels: approved, lgtm

#420 pkg/etcdenvvar: enable pprof by default
  pkg/etcdenvvar/etcd_env.go
Labels: approved, lgtm

#424 Bug 1868117: pkg/cmd/render: remove kube-client-agent as required flag
  pkg/cmd/render/options/config.go
  pkg/cmd/render/render.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#427 Bug 1871890: add current profile annotations to CVO manifests
  manifests/0000_12_etcd-operator_00_namespace.yaml
  manifests/0000_12_etcd-operator_01_config.crd.yaml
  manifests/0000_12_etcd-operator_01_operator.cr.yaml
  manifests/0000_12_etcd-operator_02_service.yaml
  manifests/0000_12_etcd-operator_03_configmap.yaml
  manifests/0000_12_etcd-operator_03_secret.yaml
  manifests/0000_12_etcd-operator_04_clusterrolebinding.yaml
  manifests/0000_12_etcd-operator_05_serviceaccount.yaml
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
  manifests/0000_12_etcd-operator_08_etcdquorumguard_deployment.yaml
  manifests/0000_12_etcd-operator_09_etcdquorumguard_pdb.yaml
  manifests/0000_90_etcd-operator_01_prometheusrole.yaml
  manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#419 Bug 1869681: handle IP migration when DNS fails on Azure IPI
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#429 bug 1872802: remove old MCO etcd quorum guard resources
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#401 Bug 1859678: Forget bootstrap etcd member IP after bootstrap
  go.mod
  pkg/etcdcli/etcdcli.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  vendor/k8s.io/utils/diff/diff.go
  vendor/k8s.io/utils/field/path.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#404 Update OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#431 Bug 1858763: bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
