Repository openshift/cluster-etcd-operator, pull requests merged in 2020-06, with the labels that each got.

#368 Silence grpc connection log noise
  cmd/cluster-etcd-operator/main.go
Labels: approved, lgtm

#370 Bug 1835238: Exclude bootstrap in the env variable ETCDCTL_ENDPOINTS
  pkg/etcdenvvar/etcd_env.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#367 Bug 1832923: Forget bootstrap etcd member IP after bootstrap
  go.mod
  pkg/etcdcli/etcdcli.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  vendor/k8s.io/utils/diff/diff.go
  vendor/k8s.io/utils/field/path.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#373 OWNERS: add sttts
  OWNERS
Labels: approved, lgtm

#374 Bug 1812570: Restart operator when metrics serving cert is modified
  manifests/0000_12_etcd-operator_06_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#371 Bug 1842431: cluster-backup.sh: error if script dependencies are not met
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#372 Bug 1840531: Adding rollbackcopy subcommand
  bindata/etcd/pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/rollbackcopy/backuputils.go
  pkg/cmd/rollbackcopy/backuputils_test.go
  pkg/cmd/rollbackcopy/etcdclientutils.go
  pkg/cmd/rollbackcopy/fileioutils.go
  pkg/cmd/rollbackcopy/rollbackcopy.go
  pkg/cmd/rollbackcopy/tarutils.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm
