Repository openshift/cluster-etcd-operator, pull requests merged in 2020-05, with the labels that each got.

#328 Bug 1830505: pkg/operator/etcdcertsigner: fix DNS SAN for peer certificates
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#332 Bug 1832901: Stop reconciling in response to global configmap events
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#339 Bug 1832919: Stop reconciling in response to global configmap events
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#340 Bug 1830510: pkg/operator/etcdcertsigner: sign peer DNS SAN with explicit FQDN
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#346 Bug 1835319: remove dead host-etcd-2 service
  bindata/bootkube/manifests/00_etcd-host-service.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#344 Bug 1813894: Stop using service ca from service account token
  go.mod
  go.sum
  manifests/0000_12_etcd-operator_03_configmap.yaml
  manifests/0000_12_etcd-operator_06_deployment.yaml
  pkg/operator/metriccontroller/client.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#348 Bug 1831664: pkg/cmd/render: Backport adding support for s390 and s390x arch
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/env.go
  pkg/cmd/render/env_test.go
  pkg/cmd/render/render.go
  pkg/etcdenvvar/etcd_env.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#341 Bug 1830505: Revert: "pkg/operator/etcdcertsigner: fix DNS SAN for peer certificates"
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#337 Bug 1825236: Fix podman auth
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#336 Bug 1823608: fix message reporting for etcdmemberscontroller
  pkg/etcdcli/etcdcli.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#349 Bug 1836374: OWNERS: add Dan Mace and Suresh Kolichala
  OWNERS
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#351 Bug 1837103: Revert "remove dead host-etcd-2 service"
  bindata/bootkube/manifests/00_etcd-host-service.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#352 Bug 1835146: Cluster restore should not stop network pods on bare-metal
  bindata/etcd/cluster-restore.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#356 Bug 1837594: pkg/operator/etcdcertsigner: sign etcd certs for 3 years
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#354 Bug 1836927: Replace etcd endpoint representation with configmap
  bindata/bootkube/manifests/00_etcd-endpoints-cm.yaml
  pkg/etcdcli/etcdcli.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#343 Bug 1832986: pkg/etcdcli: fix health checks
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/health.go
  pkg/etcdcli/health_test.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#321 Bug 1834852: Add make target to run operator with telepresence
  .gitignore
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#359 Bug 1809282: regenerate the CRD from the latest types
  manifests/0000_12_etcd-operator_01_config.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#363 Bug 1812126: increase memory and resource limits for installer and pruner pods
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/security/v1/0000_03_security-openshift_01_scc.crd.yaml
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#342 Bug 1832923: remove bootstrap annotation after bootstrapping
  pkg/etcdcli/etcdcli.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#360 Bug 1838781: pkg/etcdcli: refactor health checks
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/health.go
  pkg/etcdcli/health_test.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#358 Bug 1837630: pkg/operator/etcdcertsigner: sign etcd certs for 3 years
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#364 Bug 1832923: revert: remove bootstrap annotation after bootstrapping
  pkg/etcdcli/etcdcli.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
