Repository openshift/cluster-etcd-operator, pull requests merged in 2020-04, with the labels that each got.

#289 Bug 1819472: manifests: update CVO managed configmaps to create-only
  bindata/bootkube/config/etc-etcd-etcd-conf.yaml
  manifests/0000_12_etcd-operator_00_staticpod-rolebinding.yaml
  manifests/0000_12_etcd-operator_00_staticsync-rolebinding.yaml
  manifests/0000_12_etcd-operator_03_configmap.yaml
  manifests/0000_12_etcd-operator_03_secret.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#284 Bug 1817028: *: add an init container to stop the pod with bad revision
  bindata/etcd/pod.yaml
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#294 remove a duplicate line
  pkg/operator/starter.go
Labels: approved, lgtm, ok-to-test

#296 Bug 1822326: Add extra checks for ipv6 addresses when checking the etcd env
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#306 Bug 1817071: *: add an init container to stop the pod with bad revision
  bindata/etcd/pod.yaml
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#304 Bug 1822924: The snapshot backup must be requested from a single endpoint not multiple
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#290 Bug 1821286: fix message reporting for etcdmemberscontroller
  pkg/etcdcli/etcdcli.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#312 add relatedobjects for immediate creation by CVO
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
Labels: approved, lgtm

#308 OWNERS: add component
  OWNERS
Labels: approved, lgtm

#314 Bug 1823931: bindata/etcd/etcd-common-tools pass --authfile to podman create
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#297 Bug 1826140: add infra flag and configure raft for Azure
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#313 Bug 1827585: Add controller that watches leader changes and capture disk metrics
  go.mod
  pkg/operator/metriccontroller/client.go
  pkg/operator/metriccontroller/fsync_controller.go
  pkg/operator/starter.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#320 Bug 1823931: Fix the path for authfile used for copying the etcdctl image
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#318 Bug 1821286: Unstarted members cannot be blank in the log/event messages
  pkg/etcdcli/etcdcli.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#325 Change component name in OWNERS to 'Etcd Operator'
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#324 Bug 1829737: operator: migrate controllers to factory
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/hostendpointscontroller2/host_endpoints_controller.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#317 Bug 1825667: pkg/cmd/render: add support for s390 and s390x arch
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/env.go
  pkg/cmd/render/env_test.go
  pkg/cmd/render/render.go
  pkg/etcdenvvar/etcd_env.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
