Repository openshift/cluster-etcd-operator, pull requests merged in 2020-01, with the labels that each got.

#53 *: add cluster-etcd-operator to CVO operator payload
  Dockerfile
  Dockerfile.rhel7
  manifests/0000_12_etcd-operator_01_operator.cr.yaml
  pkg/cmd/staticsynccontroller/staticsynccontroller.go
Labels: approved, lgtm, size/S

#55 observe_etcd.go: fix numberOfInitContainers
  pkg/operator/configobservation/etcd/observe_etcd.go
Labels: approved, lgtm, size/XS

#58 *: wait for KAS rollout to succeed before cutting bootstrap
  pkg/cmd/waitforceo/waitforceo.go
  pkg/operator/bootstrapteardown/teardown.go
  pkg/operator/bootstrapteardown/waitforceo.go
  pkg/operator/bootstrapteardown/waitforceo_test.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, lgtm, size/L

#66 Bug 1796965: *: reduce the bootstrap time by fixing implementation details
  pkg/cmd/staticsynccontroller/staticsynccontroller.go
  pkg/operator/bootstrapteardown/waitforceo.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
