Repository openshift/cluster-etcd-operator, pull requests merged in 2020-10, with the labels that each got.

#462 flowschema for etcd operator traffic
  manifests/0000_12_etcd-operator_10_flowschema.yaml
Labels: approved, lgtm

#459 *: enable pprof profiler for operator
  manifests/0000_12_etcd-operator_06_deployment.yaml
Labels: approved, lgtm

#463 Updating cluster-etcd-operator builder & base images to be consistent with ART
  Dockerfile.rhel7
Labels: approved, lgtm

#464 bug 1888015: bump library-go to pick up static pod graceful timeout workaround
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#443 [release-4.4] Bug 1877965: Use restore pod yaml from the backup when restoring
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  go.mod
  go.sum
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#467 OWNERS: change component to Etcd
  OWNERS
Labels: approved, lgtm

#474 Use etcd's /health endpoint for readiness checking
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#476 *:bump library-go
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/component-base/logs/registry.go
  vendor/modules.txt
Labels: approved, lgtm

#477 bump library-go for static pod uid
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm

#479 bug 1888026: bump library-go for static pod uid
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#481 pkg/operator: remove legacy api
  pkg/operator/api/scaling.go
Labels: approved, lgtm

#438 Bug 1877374: Render bootstrap certificates
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
