Repository openshift/cluster-etcd-operator, pull requests merged in 2020-03, with the labels that each got.

#226 waits for ports before starting etcd member
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, size/S

#224 [release-4.4] Bug 1809682: sync with master
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  go.mod
  go.sum
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#228 Bug 1810276: bindata/etcd: fix etcdctl trap
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#229 bug 1810133: remove usage of host-etcd
  pkg/operator/hostendpointscontroller/host_endpoints_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#233 remove dns lookups
  bindata/etcd/openshift-recovery-tools
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/dnshelpers/util.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/interfaces.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XL

#235 remove all non-IPs from peer URL
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
Labels: approved, lgtm, size/XS

#220 Bug 1810469: The disaster recovery scripts need simplification
  bindata/etcd/etcd-common-tools
  bindata/etcd/etcd-member-remove.sh
  bindata/etcd/etcd-restore-backup.sh
  bindata/etcd/etcd-snapshot-backup.sh
  bindata/etcd/etcd-snapshot-restore.sh
  bindata/etcd/openshift-recovery-tools
  bindata/etcd/scripts-cm.yaml
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#239 [release-4.4] Bug 1811064: sync with master 03-06
  bindata/etcd/openshift-recovery-tools
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/dnshelpers/util.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/interfaces.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
  pkg/operator/hostendpointscontroller/host_endpoints_controller.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XXL

#240 Bug 1810997: pkg/operator/etcdcertsigner: always include ::1 in cert SAN
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#236 add events for membership changes
  pkg/etcdcli/etcdcli.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/M

#246 The data-dir should be /var/lib/etcd instead of /var/lib/etcd/member …
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, size/XS

#238 cache the client based on the endpoints to avoid reconstruction
  pkg/etcdcli/etcdcli.go
Labels: approved, lgtm, size/M

#249 Bug 1812236: etcdctl cannot find cert
  pkg/etcdenvvar/etcd_env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#254 Bug 1812583: Normalize CPU requests on masters
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#257 bindata/etcd: backup and restore all static pods
  bindata/etcd/etcd-snapshot-backup.sh
  bindata/etcd/etcd-snapshot-restore.sh
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, size/L

#265 Copy files from etcd-scripts to /usr/local/bin for convenience
  bindata/etcd/etcd-member-remove.sh
  bindata/etcd/etcd-snapshot-backup.sh
  bindata/etcd/etcd-snapshot-restore.sh
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#269 [release-4.4] Bug 1814292: Copy files from etcd-scripts to /usr/local/bin for convenience
  bindata/etcd/etcd-member-remove.sh
  bindata/etcd/etcd-snapshot-backup.sh
  bindata/etcd/etcd-snapshot-restore.sh
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#268 Bug 1814479: bindata/etcd: run etcdctl inside of container
  bindata/etcd/etcd-common-tools
  bindata/etcd/etcd-member-remove.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#270 bump library-go to migrate controllers to factory
  go.mod
  go.sum
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/controller/manager/controller_manager.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#272 Bug 1815203: bindata/etcd: rename DR scripts to cluster-backup and cluster-restore
  bindata/etcd/cluster-backup.sh
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-member-remove.sh
  bindata/etcd/scripts-cm.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/scriptcontroller/scriptcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm

#287 Bug 1810181: Remove wildcard COPY form Docker
  Dockerfile.rhel7
Labels: approved, bugzilla/valid-bug, lgtm
