Repository openshift/cluster-etcd-operator, pull requests merged in 2020-11, with the labels that each got.

#484 add current profile annotations to CVO manifests
  manifests/0000_12_etcd-operator_10_flowschema.yaml
Labels: approved, lgtm

#486 picks up setting `TCP_USER_TIMEOUT` socket option
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
  vendor/github.com/openshift/library-go/pkg/network/dialer.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/modules.txt
Labels: approved, lgtm

#482 *: remove all MCO tolerations
  pkg/operator/starter.go
Labels: approved, lgtm

#485 Bug 1892288: pkg/etcdcli: add IsQuorumFaultTolerant
  go.mod
  go.sum
  pkg/etcdcli/health.go
  pkg/etcdcli/health_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  vendor/go.etcd.io/etcd/pkg/mock/mockserver/doc.go
  vendor/go.etcd.io/etcd/pkg/mock/mockserver/mockserver.go
  vendor/golang.org/x/oauth2/README.md
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/grpclog/grpclog.go
  vendor/google.golang.org/grpc/grpclog/logger.go
  vendor/google.golang.org/grpc/grpclog/loggerv2.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/logging.go
  vendor/google.golang.org/grpc/internal/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/grpclog/prefixLogger.go
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#469 * remove 4.3 tolerations
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#495 Bug 1895509: Revert "Bug 1837540: Use restore pod yaml from the backup when restoring"
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#494 Bug 1894267: Remove the rollbackcopier
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#500 Revert "Use etcd's /health endpoint for readiness checking"
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#501 Remove unused cruft
  Dockerfile.rhel7
  bindata/bootkube/config/bootstrap-config-overrides.yaml
  bindata/bootkube/config/config-overrides.yaml
  bindata/bootkube/manifests/00_etcd-host-service-endpoints.yaml
  bindata/bootkube/manifests/00_etcd-host-service.yaml
  bindata/bootkube/manifests/configmap-initial-etcd-serving-ca.yaml
  bindata/etcd/defaultconfig.yaml
  pkg/cmd/render/render.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/hostendpointscontroller2/host_endpoints_controller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm
