Repository openshift/cluster-etcd-operator, pull requests merged in 2020-02, with the labels that each got.

#72 Bug 1797491: manifests: Drop Deprecated etcd metrics
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#68 Bug 1797122: add hack for KAS rollouts, make cmc chattier
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#78 bug 1798219: use dynamic client instead of taking an MCO dependency
  pkg/cmd/staticpodcontroller/staticpodcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#82 bug 1798222: the etcd clusteroperator should be etcd
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#84 Sixtythree
  pkg/cmd/waitforceo/waitforceo.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/teardown.go
  pkg/operator/bootstrapteardown/waitforceo.go
  pkg/operator/bootstrapteardown/waitforceo_test.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/XL

#81 bug 1798582: remove status controller copy
  pkg/operator/starter.go
  pkg/operator/statuscontroller/condition.go
  pkg/operator/statuscontroller/statuscontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#85 bug 1798582: *: fixups: remove unmanaged in waitforceo.go, fix typo
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/waitforceo.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#88 bug 1798642: add basic static pod operator
  Makefile
  bindata/etcd/cm.yaml
  bindata/etcd/defaultconfig.yaml
  bindata/etcd/ns.yaml
  bindata/etcd/pod-cm.yaml
  bindata/etcd/pod.yaml
  bindata/etcd/sa.yaml
  bindata/etcd/svc.yaml
  bindata/v4.3.0/etcd/operator-config.yaml
  cmd/cluster-etcd-operator/main.go
  go.mod
  go.sum
  manifests/0000_12_etcd-operator_06_deployment.yaml
  pkg/cmd/render/render.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/retry.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/retry/wait.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/staticpod.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/int32.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/compatibility.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#95 bug 1800313: add env vars
  bindata/etcd/pod.yaml
  go.mod
  go.sum
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#104 Bug 1800810: pkg/operator/clustermembercontroller: add WithBlock() to dial options
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/hostetcdendpointcontroller/members.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#103 bug 1800313: the etcd process
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner2/etcdcertsignercontroller.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#109 Bug 1801344: vendor: bump build-machinery-go
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#99 Bug 1801299: go.mod: bump go version 1.13
  go.mod
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#90 Bug 1798696: etcd operator does not reference etcd images for cvo substitution
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/0000_12_etcd-operator_06_static_pod_demonset.yaml
  manifests/0000_12_etcd-operator_06_static_sync_demonset.yaml
  manifests/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#98 bug 1801769: use etcd static pod status to build host endpoints
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/hostendpointscontroller/host_endpoints_controller.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go
  pkg/operator/hostetcdendpointcontroller/hostendpointcontroller_test.go
  pkg/operator/hostetcdendpointcontroller/members.go
  pkg/operator/hostetcdendpointcontroller/members_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#73 Bug 1797897: pkg/cmd/waitforkube: don't wait if etcd has previously been initialed as member
  pkg/cmd/waitforkube/waitforkube.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#123 Bug 1801984: host-etcd endpoints should always contain all etcd nodes
  pkg/operator/hostendpointscontroller/host_endpoints_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#52 Bug 1788231: pkg/cmd/render: improve IPv6 support
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#125 Bug 1802228: For etcd discovery domain, watch infrastructure not controller config
  pkg/operator/etcdcertsigner2/etcdcertsignercontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#118 bug 1801877: simplify the bootstrapteardown controller
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/waitforceo.go
  pkg/operator/bootstrapteardown/waitforceo_test.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#119 Bug 1802219: add etcdcli that can be used across the project.
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#132 Bug 1802368: etcdcli: add UnhealthyMemberLister, bootstrapteardown: use the EtcdClient interface
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#131 bug 1802245: fix host endpoint hotloop
  pkg/operator/hostendpointscontroller/host_endpoints_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#137 Bug 1802748: old clustermembercontroller: use EtcdClient interface
  pkg/etcdcli/etcdcli.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#136 bug 1802578: fix the etcd serving metrics
  pkg/operator/etcdcertsigner2/etcdcertsignercontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#147 Bug 1803269: render: fix listening addresses in IPv6 case
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#143 Bug 1801898: remove dependency on node internal DNS name
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#162 bug 1801397: Make existing pdb work
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/guardbudget/guard_budget_controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#164 bug 1804439: clean up packages
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#168 Bug 1802664: *: fix etcdmemberscontroller
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#165 Bug 1804751: remove guard budget controller
  manifests/0000_12_etcd-operator_00_pdb-rolebinding.yaml
  manifests/0000_12_etcd-operator_08_etcdquorumguard_pdb.yaml
  manifests/0000_12_etcd-operator_09_etcdquorumguard_deployment.yaml
  manifests/image-references
  pkg/operator/guardbudget/guard_budget_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#172 Bug 1804921: Exclude etcd operator from hosted control plane deployments
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#166 bug 1804439: add debugging to clustermembercontroller and clean up add bug
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#154 Bug 1804960: Revert: render: fix listening addresses in IPv6 case
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#114 pkg/operator/targetconfigcontroller: fix configmap typo
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/XS

#176 Bug 1805096: [release 4.4] remove guard_budget_controller
  manifests/0000_12_etcd-operator_00_pdb-rolebinding.yaml
  manifests/0000_12_etcd-operator_08_etcdquorumguard_pdb.yaml
  manifests/0000_12_etcd-operator_09_etcdquorumguard_deployment.yaml
  manifests/image-references
  pkg/operator/guardbudget/guard_budget_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#124 bug 1801938: add host-etcd-2 which will never list the bootstrap etcd as an endpoi…
  bindata/bootkube/manifests/00_etcd-host-service-endpoints.yaml
  bindata/bootkube/manifests/00_etcd-host-service.yaml
  pkg/cmd/render/render.go
  pkg/operator/hostendpointscontroller2/host_endpoints_controller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#181 bug 1804960: Merge 4.5 into 4.4
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/0000_12_etcd-operator_07_clusteroperator.yaml
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#179 bug 1805421: allow bootstrap server to terminate before removing etcd-bootstrap fr…
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/waitforceo.go
  pkg/operator/bootstrapteardown/waitforceo_test.go
  pkg/operator/starter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#173 bug 1804913: make ipv6 support a little better
  pkg/dnshelpers/util.go
  pkg/etcdcli/etcdcli.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/util.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/hostendpointscontroller/host_endpoints_controller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#175 pkg/cmd/render: populate bootstrapIP from local interfaces
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  pkg/cmd/render/options/config.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/etcdcli/etcdcli.go
Labels: approved, lgtm, size/L

#185 bug 1805807: call the discovery-etcd-initial-cluster
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#195 bug 1805809: merge master into 4.4
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  bindata/etcd/pod.yaml
  pkg/cmd/render/options/config.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/etcdcli/etcdcli.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#200 bug 1806723: use correct IP for bootstrap host env vars
  pkg/dnshelpers/util.go
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#198 bug 1806694: place etcd certificates in a known location
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/gogo/protobuf/gogoproto/gogo.pb.go
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_merge.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor/descriptor.pb.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#194 bug 1806530: only add members when the etcd container is unready
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#202 Bug 1807018: etcdcli: fix out-of-bounds panic
  pkg/etcdcli/etcdcli.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#205 bug 1807167: update to master
  bindata/etcd/restore-pod-cm.yaml
  bindata/etcd/restore-pod.yaml
  go.mod
  go.sum
  pkg/dnshelpers/util.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/gogo/protobuf/gogoproto/gogo.pb.go
  vendor/github.com/gogo/protobuf/proto/encode.go
  vendor/github.com/gogo/protobuf/proto/lib.go
  vendor/github.com/gogo/protobuf/proto/properties.go
  vendor/github.com/gogo/protobuf/proto/table_marshal.go
  vendor/github.com/gogo/protobuf/proto/table_merge.go
  vendor/github.com/gogo/protobuf/proto/table_unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text.go
  vendor/github.com/gogo/protobuf/protoc-gen-gogo/descriptor/descriptor.pb.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/openshift/api/README.md
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/network/v1/001-clusternetwork-crd.yaml
  vendor/github.com/openshift/api/network/v1/002-hostsubnet-crd.yaml
  vendor/github.com/openshift/api/network/v1/003-netnamespace-crd.yaml
  vendor/github.com/openshift/api/network/v1/004-egressnetworkpolicy-crd.yaml
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XL

#201 use correct IP for bootstrap host env vars
  pkg/dnshelpers/util.go
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, size/M

#196 [4.4] only add members when the etcd container is unready
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, do-not-merge/hold, size/S

#203 [Bug 1807054]: fix recovery of master nodes restarting at the same time
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, size/XS

#211 [Bug 1807493]: update library-go for substitution
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#199 [Bug 1807493]: add the restore command to restore pod
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, size/M

#212 [Bug 1807493]: Add recovery scripts to ceo
  bindata/etcd/etcd-member-remove.sh
  bindata/etcd/etcd-restore-backup.sh
  bindata/etcd/etcd-snapshot-backup.sh
  bindata/etcd/openshift-recovery-tools
  bindata/etcd/scripts-cm.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, size/XXL

#210 [Bug 1807493]: add scripts to files laid down to host
  bindata/etcd/etcd-restore-backup.sh
  bindata/etcd/scripts-cm.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
Labels: approved, size/L

#215 Bug 1807976: sync with master
  bindata/etcd/etcd-member-remove.sh
  bindata/etcd/etcd-restore-backup.sh
  bindata/etcd/etcd-snapshot-backup.sh
  bindata/etcd/openshift-recovery-tools
  bindata/etcd/restore-pod.yaml
  bindata/etcd/scripts-cm.yaml
  go.mod
  go.sum
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#216 [Bug 1808105]: bump(make sh files executable)
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#207 Bug 1805981: oc rsh to an etcd pod needs to have etcdctl "just work"
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#218 Bug 1806700: pkg/operator/targetconfigcontroller: add platform raft tunables
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#217 [Bug 1808493]: add ca-bundles to fixed locations and use the for restore pod
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/etcd_env.go
Labels: approved, lgtm, size/L
