Repository openshift/cluster-etcd-operator, pull requests merged in 2020-12, with the labels that each got.

#502 Bug 1844727: Use socket readiness probe to avoid generating zombies
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#497 Bug 1897543: DR: Make restore pod yaml specific to restoring node
  bindata/etcd/cluster-restore.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#449 Introduce bootstrap scaling strategies
  bindata/bootkube/manifests/00_openshift-etcd-ns.yaml
  pkg/cmd/render/render.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/unsupported_override.go
  pkg/operator/ceohelpers/unsupported_override_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
Labels: approved, lgtm

#504 Bug 1898954: Backup script should get the latest revision of static-pod-resources …
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#509 Bug 1906875: Provide an option force backup even when API is not available to check the health.
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
