Repository openshift/cluster-etcd-operator, pull requests merged in 2020-09, with the labels that each got.

#418 Bug 1850057: etcd-pod: Use ionice -c2 -n0
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#432 Bug 1874552: *: migrate logger form klog to klog/v2
  go.mod
  pkg/cmd/backuprestore/backuprestore.go
  pkg/cmd/backuprestore/backuputils.go
  pkg/cmd/backuprestore/crioclient.go
  pkg/cmd/backuprestore/etcdclientutils.go
  pkg/cmd/backuprestore/restoreutils.go
  pkg/cmd/backuprestore/tarutils.go
  pkg/cmd/render/bootstrap_ip.go
  pkg/cmd/render/bootstrap_ip_linux.go
  pkg/cmd/render/render.go
  pkg/cmd/waitforceo/waitforceo.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/operator/bootstrapteardown/waitforceo.go
  pkg/operator/ceohelpers/unsupported_override.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/hostendpointscontroller2/host_endpoints_controller.go
  pkg/operator/metriccontroller/fsync_controller.go
  pkg/operator/starter.go
  test/e2e/framework/clientset.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#435 Bug 1876858: manifests: rename operator container to be more descriptive
  manifests/0000_12_etcd-operator_06_deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#436 Bug 1837540: Use restore pod yaml from the backup when restoring
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, release-note

#434 Bug 1874597: static-pod-installer: remove deadlock by recreating installers that disappear
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/build/v1/generated.pb.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#426 Bug 1840358: etcd-quorum-guard remove toleration timeouts
  manifests/0000_12_etcd-operator_08_etcdquorumguard_deployment.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#444 Bug 1881082: Expose etcd raft term as a metric
  pkg/etcdcli/health.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#447 Bug 1880313: vendor: bump k8s to 1.18.6 to fix bug in reflector not recovering from "Too large resource version"
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#442 [release-4.5] Bug 1877930: Use restore pod yaml from the backup when restoring
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#451 Bug 1881082: remove erroneously specified label drop rules
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#454 Bug 1883610: Use more reliable ss in place of lsof
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#455 Bug 1883689: Add validation for logLevel
  Dockerfile.rhel7
  go.mod
  go.sum
  manifests/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#457 Bug 1883772: pkg/operator/clustermembercontroller: resync every minute
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
