Repository openshift/cluster-etcd-operator, pull requests merged in 2021-05, with the labels that each got.

#573 Bug 1952684: pkg/operator/metriccontroller: dont panic on invalid response from prom client
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#583 OWNERS: add lilic as reviewer
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm

#584 Bug 1952684: pkg/operator/metriccontroller: check vector length
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#579 Bug 1952268: Increase inertia duration for the EtcdMembersDegraded condition
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#580 Bug 1946607: bindata/etcd: improve readinessProbe checks by dialing unix socket target
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#578 Bug 1954073: bindata, pkg: Propagate operator log level to etcd itself
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#585 docs: Initial documentation for discover init cluster along with a flowchart
  docs/discover-initial-cluster-flowchart.png
  docs/discover-initial-cluster.md
Labels: approved, bugzilla/valid-bug, lgtm

#587 Bug 1902247: pkg/dnshelpers: fallback to spec if status is not populated for serviceNetwork
  pkg/dnshelpers/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#586 Bug 1958245: etcd/pod: print static pod revision in logs
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#591 Bug 1902247: pkg/dnshelpers: cleanup dead code
  pkg/dnshelpers/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#599 Bug 1963871: Move back to Golang 1.15 as in o/release
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#582 Bug 1955418: manifests: Shift FlowSchema to level 50
  manifests/0000_50_etcd-operator_flowschema.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#602 Bug 1963871: bump(*): Update the go version to 1.16
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
