Repository openshift/cluster-etcd-operator, pull requests merged in 2021-02, with the labels that each got.

#536 Bug 1924913: A valid etcd endpoint should have the URL scheme prepended.
  pkg/cmd/rollbackcopy/backuputils.go
  pkg/cmd/rollbackcopy/etcdclientutils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#534 Bug 1925586: pkg/operator/metriccontroller: cleanup transports
  pkg/operator/metriccontroller/client.go
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#527 Adding single node ocp cluster support
  bindata/etcd/quorumguard-deployment.yaml
  go.mod
  go.sum
  lib/resourceapply/apps.go
  lib/resourceapply/policyv1beta1.go
  lib/resourcemerge/apps.go
  lib/resourcemerge/core.go
  lib/resourcemerge/meta.go
  lib/resourcemerge/policyv1beta1.go
  manifests/0000_12_etcd-operator_09_etcdquorumguard_pdb.yaml
  pkg/etcdenvvar/envvarcontroller.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/control_plane_topology.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/api/Dockerfile.build
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/generated.proto
  vendor/github.com/openshift/api/project/v1/types.go
  vendor/github.com/openshift/api/project/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#540 Improve cert controller detection and correction of invalid certs
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, lgtm

#543 Bug 1929359: pkg/operator/quorumguardcontroller: use cli image from release payload
  manifests/0000_12_etcd-operator_06_deployment.yaml
  manifests/image-references
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#542 Refactor creation of aggregated cert secrets
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/testutils/testutils.go
Labels: approved, lgtm

#516 switch to v1beta1 for the p&f APIs
  manifests/0000_12_etcd-operator_10_flowschema.yaml
Labels: approved, lgtm

#544 Manage one aggregated cert secret rather than one per cert type
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  docs/etcd-tls-assets.md
  pkg/cmd/render/render.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm
