Repository openshift/cluster-etcd-operator, pull requests merged in 2021-09, with the labels that each got.

#653 Bug 1997347: pkg/operator/upgradebackupcontroller: update cluster operator status
  pkg/operator/starter.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#655 OWNERS: add lilic as approver.
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug

#657 Bug 1997347: pkg/cmd/verify: bug fixes and improvements
  bindata/etcd/cluster-backup-pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/verify/backupstorage.go
  pkg/cmd/verify/verify.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#652 Bug 1999777: [release-4.8]: pkg/operator: add cluster backup upgrade controller
  bindata/etcd/cluster-backup-pod.yaml
  bindata/etcd/etcd-common-tools
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/verify/backupstorage.go
  pkg/cmd/verify/verify.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/helpers.go
  pkg/etcdcli/interfaces.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#661 Bug 2001856: bump library-go and dependencies
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/deprecated_insecure_serving.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: approved, lgtm

#664 pkg/cmd/render: disallow placeholder IPs
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm

#670 OWNERS: add hasbro17 to reviewers
  OWNERS
Labels: approved, lgtm

#672 pkg/operator: remove stale condition controller
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm

#654 Bug 1990489: Reintroduce etcdHighNumberOfFailedGRPCRequests alert for non metal ipi clusters
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#660 Bug 2006975: Suppress noisy logs and improve client errors
  pkg/cmd/backuprestore/backuprestore.go
  pkg/cmd/backuprestore/backuputils.go
  pkg/cmd/backuprestore/etcdclientutils.go
  pkg/cmd/verify/backupstorage.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/helpers.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/defragcontroller/defragcontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
Labels: approved, lgtm

#678 bindata/bootkube/bootstrap-manifests: add etcdctl container to bootstrap-etcd
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
Labels: approved, lgtm

#680 pkg: Pass context through to functions
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/helpers.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
Labels: approved, lgtm
