Repository openshift/cluster-etcd-operator, pull requests merged in 2021-10, with the labels that each got.

#676 Bug 2004451: pkg/operator/upgradebackupcontroller: fix backup dir name in status condition
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#684 pkg/operator/metriccontroller: Fix query
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, lgtm

#681 podsecurity: enforce privileged for openshift-etcd namespace
  bindata/etcd/ns.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#663 Bug 2003540: bump library-go
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/go.mod
  vendor/github.com/openshift/api/go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/server/deprecated_insecure_serving.go
  vendor/k8s.io/apiserver/pkg/server/secure_serving.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/store.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, staff-eng-approved
