Repository openshift/cluster-etcd-operator, pull requests merged in 2021-04, with the labels that each got.

#553 Bug 1927942: pkg/etcdenvvar: enable SO_REUSEADDR
  pkg/etcdenvvar/etcd_env.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#562 Bug 1948040: *: enable zap as default logger
  bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#561 Bug 1948553: bindata, pkg: Propagate operator log level to etcd itself
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#564 Bug 1949418: bump(*): vendor update
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/client/transport.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/unstructured.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#560 Add management workload annotations
  bindata/etcd/ns.yaml
  bindata/etcd/pod.yaml
  manifests/0000_12_etcd-operator_00_namespace.yaml
  manifests/0000_12_etcd-operator_06_deployment.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#567 Bug 1950934: pkg/etcdenvvar/etcd_env.go: Sort endpoints to prevent rollout
  pkg/etcdenvvar/etcd_env.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#570 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#574 Bug 1953563: Add .ci-operator.yaml with build_root_image
  .ci-operator.yaml
  Makefile
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#569 Rename workload annotations
  bindata/etcd/pod.yaml
  manifests/0000_12_etcd-operator_06_deployment.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#576 Bug 1952266: Don't set operator version before operands update
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
