Repository openshift/cluster-etcd-operator, pull requests merged in 2021-08, with the labels that each got.

#634 Bug 1986829: metrics: use client cert auth for metrics scraping
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#626 Bug 1701154: Enable etcdHighNumberOfFailedGRPCRequests alerts
  jsonnet/main.jsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#637 Revert "Bug 1701154: Enable etcdHighNumberOfFailedGRPCRequests alerts"
  jsonnet/main.jsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#635 Bug 1989335: pkg/operator/targetconfigcontroller: block rollout and report on missing external resource
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#624 [release-4.6] Bug 1979585: Validate the status of the etcd snapshot during backup and restore
  bindata/etcd/cluster-backup.sh
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#640 Bug 1993757: bindata/etcd: remove unix socket from advertised list
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#631 Bug 1957498: Clean up tech debt
  lib/resourceapply/policyv1beta1.go
  lib/resourcemerge/policyv1beta1.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#639 Bug 1980465: pkg/etcdenvvar: warn on apply duration over 200ms
  pkg/etcdenvvar/etcd_env.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#644 Bug 1994707: pkg/etcdcli: provide clear error on status check for unstarted etcd member
  pkg/etcdcli/etcdcli.go
  pkg/operator/defragcontroller/defragcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#646 Bug 1994986: test/e2e/etcdctl_test.go: Skip check perf test as we disabled it
  test/e2e/etcdctl_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#645 Bug 1997207: Pass context into clientv3.Config to use same context
  pkg/cmd/monitor/monitor.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#648 Bug 1993800: Bump library-go to include backoff fix of installers
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high
