Repository openshift/cluster-etcd-operator, pull requests merged in 2021-12, with the labels that each got.

#708 pkg/etcdenvvar: set max learners based on desired control plane replicas
  pkg/cmd/render/env.go
  pkg/cmd/render/env_test.go
  pkg/cmd/render/render.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/operatorclient/interfaces.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm

#713 bump(library-go): to gather a fix for static pod UID version
  cmd/cluster-etcd-operator/main.go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
  vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_linux.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_others.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm

#720 update OWNERS
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug

#719 Bump library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug

#725 Bug 2034484: fix:library-go nil pointer issue
  go.mod
  go.sum
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/resource_cache.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/leaderelection/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/clientgo/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/restclient/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
