Repository openshift/cluster-etcd-operator, pull requests merged in 2021-01, with the labels that each got.

#517 Bug 1851351: Remove stale EtcdMemberIPMigratorDegraded condition
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#380 Bug 1848516: cluster-backup.sh: error if script dependencies are not met
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#523 Bug 1851810: *: ensure etcd listens on strong ciphers
  pkg/etcdenvvar/etcd_env.go
  pkg/etcdenvvar/etcd_env_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#461 Bug 1882176: Validate certs for the current IP address of the node
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#524 OWNERS: add marun
  OWNERS
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#525 Bug 1916853: pkg/operator: ensure etcd endpoints cm
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#530 Bug 1917411: pkg/operator: ensure etcd endpoints configmap
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#519 docs: add maintenance section
  docs/HACKING.md
Labels: approved, bugzilla/valid-bug, lgtm

#532 Bug 1907872: Make dual stack bootstrapping more reliable
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#456 Bug 1871170: test/e2e: add etcdctl sanity test
  go.mod
  test/e2e/etcdctl_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#529 Add summary tables to tls asset docs
  docs/etcd-tls-assets.md
Labels: approved, bugzilla/valid-bug, lgtm

#535 Bug 1920159: CPU requests overstate actual needs
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#521 Bug 1915560: operator: remove EtcdMemberIPMigratorDegraded stale condition
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
