Repository openshift/cluster-etcd-operator, pull requests merged in 2021-06, with the labels that each got.

#608 Bug 1924422: go.mod, go.sum: Replace gogo/protobuf with v1.3.2
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONDUCT.md
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#601 Bug 1966813: Update the flowchart to accommodate modified logic
  docs/discover-initial-cluster-flowchart.png
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#594 [release-4.7] Bug 1958416: pkg/dnshelpers: fallback to spec if status is not populated for serviceNetwork
  pkg/dnshelpers/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#603 Bug 1965024: Validate the status of the etcd snapshot during backup and restore
  bindata/etcd/cluster-backup.sh
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#606 Rotate serving certs when duration less than minimum percent
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, lgtm

#597 pkg/etcdenvvar: bump ETCD_QUOTA_BACKEND_BYTES to 8GB
  pkg/etcdenvvar/etcd_env.go
Labels: approved, lgtm

#604 Bug 1965535: [release-4.6] Improve cert controller detection and correction of invalid certs
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#618 Bug 1976988: [release-4.7]: Increase inertia duration for the EtcdMembersDegraded condition
  pkg/operator/starter.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
