Repository openshift/cluster-etcd-operator, pull requests merged in 2022-08, with the labels that each got.

#901 [release-4.9] Bug 2111432: Add etcd pod liveness and readiness probes
  bindata/etcd/pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/readyz/readyz.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#894 vendor upstream alerts
  jsonnet/jsonnetfile.lock.json
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm

#893 [release-4.11] Bug 2108595: Cherrypick move etcd monitoring dashboard…
  hack/generate.sh
  jsonnet/dashboard.jsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#897 Bug 2089199: Remove etcd dashboards from Hypershift
  jsonnet/dashboard.jsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_20_etcd-operator_00_namespace.yaml
  manifests/0000_20_etcd-operator_01_operator.cr.yaml
  manifests/0000_20_etcd-operator_02_service.yaml
  manifests/0000_20_etcd-operator_03_configmap.yaml
  manifests/0000_20_etcd-operator_03_secret.yaml
  manifests/0000_20_etcd-operator_04_clusterrolebinding.yaml
  manifests/0000_20_etcd-operator_05_serviceaccount.yaml
  manifests/0000_20_etcd-operator_10_flowschema.yaml
  manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
  manifests/0000_90_etcd-operator_01_prometheusrole.yaml
  manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#726 Adding cluster-etcd-operator sub command: ensure-env
  bindata/etcd/pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/ensureenv/ensureenv.go
  pkg/cmd/ensureenv/ensureenv_test.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#910 Set default container in etcd
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#905 [release-4.10] Bug 2118731: ensure healthy quorum before config update
  pkg/etcdcli/health.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/etcdenvvar/fake_envvar.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/control_plane_topology.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/operator/ceohelpers/qourum_check_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#914 Revert "Adding cluster-etcd-operator sub command: ensure-env"
  bindata/etcd/pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/ensureenv/ensureenv.go
  pkg/cmd/ensureenv/ensureenv_test.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#918 OCPBUGS-675: add nil check in checkSingleMemberHealth()
  pkg/etcdcli/health.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
