Repository openshift/cluster-etcd-operator, pull requests merged in 2022-04, with the labels that each got.

#782 refactors the member removal controller
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
Labels: approved, lgtm

#780 ClusterMemberController adds members whose machines are not pending deletion
  pkg/etcdcli/helpers.go
  pkg/operator/ceohelpers/common.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/starter.go
Labels: approved, lgtm

#759 Bug 2053596: Increase IBMCloud VPC heartbeat timeout to 500ms and leader election timeout to 2500ms
  pkg/cmd/render/env.go
  pkg/cmd/render/env_test.go
  pkg/etcdenvvar/etcd_env.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#784 adds attemptToRemoveLearningMember to the cluster member removal controller
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Labels: approved, lgtm

#763 Bug 2063831: replace quorumguard and add readyz server
  bindata/etcd/pod.yaml
  bindata/etcd/quorumguard-deployment.yaml
  cmd/cluster-etcd-operator/main.go
  lib/resourceapply/apps.go
  lib/resourcemerge/apps.go
  manifests/0000_20_etcd-operator_06_deployment.yaml
  pkg/cmd/readyz/readyz.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/quorumguardcleanup/quorumguardcleanupcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
  pkg/operator/starter.go
  test/e2e/etcquorumguard_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#783 no pending on etcdHighNumberOfLeaderChanges 1st 1h
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm

#787 Bug 2075015: Revert "replace quorumguard and add readyz server"
  bindata/etcd/pod.yaml
  bindata/etcd/quorumguard-deployment.yaml
  cmd/cluster-etcd-operator/main.go
  lib/resourceapply/apps.go
  lib/resourcemerge/apps.go
  manifests/0000_20_etcd-operator_06_deployment.yaml
  pkg/cmd/readyz/readyz.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/quorumguardcleanup/quorumguardcleanupcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
  pkg/operator/starter.go
  test/e2e/etcquorumguard_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#789 Bug 2063831: Replace quorumguard and add readyz server
  bindata/etcd/pod.yaml
  bindata/etcd/quorumguard-deployment.yaml
  cmd/cluster-etcd-operator/main.go
  lib/resourceapply/apps.go
  lib/resourcemerge/apps.go
  manifests/0000_20_etcd-operator_06_deployment.yaml
  pkg/cmd/readyz/readyz.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/quorumguardcleanup/quorumguardcleanupcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller.go
  pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
  pkg/operator/starter.go
  test/e2e/etcquorumguard_test.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#791 adds attemptToRemoveLearningMember to the cluster member removal controller
  pkg/operator/ceohelpers/common.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Labels: approved, lgtm

#779 member removal part two
  go.mod
  pkg/operator/ceohelpers/common.go
  pkg/operator/ceohelpers/common_test.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/configobservation/controlplanereplicascount/observe_control_plane_replicas_count.go
  pkg/operator/configobservation/controlplanereplicascount/observe_control_plane_replicas_count_test.go
  pkg/operator/configobservation/interfaces.go
Labels: approved, lgtm

#792 Update owners with new team members
  OWNERS
Labels: approved, lgtm

#790 ClusterMemberController adds members whose machines are not pending deletion
  pkg/etcdcli/helpers.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/starter.go
Labels: approved, lgtm

#781 introduces MachineDeletionHooksController
  pkg/operator/machinedeletionhooks/machinedeletionhooks.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go
  pkg/operator/starter.go
  test/e2e/vertical_scaling_test.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machine.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machine_client.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machinehealthcheck.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/fake/fake_machineset.go
  vendor/github.com/openshift/library-go/test/library/apiserver/apiserver.go
  vendor/github.com/openshift/library-go/test/library/client.go
  vendor/github.com/openshift/library-go/test/library/library.go
  vendor/github.com/openshift/library-go/test/library/pod_same_revision.go
  vendor/modules.txt
Labels: approved, lgtm

#795 exports common functions used by the scaling controllers
  pkg/operator/ceohelpers/common.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
Labels: approved, lgtm

#796 Bug 2076831: fixing client readyz leak
  .gitignore
  pkg/cmd/readyz/readyz.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#793 Bug 2076773: Update owners to add new team members
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#799 Bug 2076793: pkg/operator/upgradebackupcontroller: Pivot from Failing to ReleaseAccepted
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#800 Bug 2077833: add more logging
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#805 clustermemberremovalcontroller must examine cluster health before removing a member
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Labels: approved, lgtm

#808 fire an event on successfull member removal
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Labels: approved, lgtm

#798 Bug 2079724: manually disable defrag
  pkg/operator/defragcontroller/defragcontroller.go
  pkg/operator/defragcontroller/defragcontroller_test.go
  pkg/operator/starter.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
