Repository openshift/cluster-etcd-operator, pull requests merged in 2022-09, with the labels that each got.

#920 add perf metric documentation
  docs/performance-metrics.md
Labels: approved, lgtm, tide/merge-method-squash

#922 OCPBUGS-675: preserve log message on failures
  pkg/etcdcli/health.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#909 [release-4.11] Bug 2108595: Cherrypick remove etcd dashboards from Hypershift
  jsonnet/dashboard.jsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_20_etcd-operator_00_namespace.yaml
  manifests/0000_20_etcd-operator_01_operator.cr.yaml
  manifests/0000_20_etcd-operator_02_service.yaml
  manifests/0000_20_etcd-operator_03_configmap.yaml
  manifests/0000_20_etcd-operator_03_secret.yaml
  manifests/0000_20_etcd-operator_04_clusterrolebinding.yaml
  manifests/0000_20_etcd-operator_05_serviceaccount.yaml
  manifests/0000_20_etcd-operator_10_flowschema.yaml
  manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
  manifests/0000_90_etcd-operator_01_prometheusrole.yaml
  manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
  manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#912 OCPBUGS-614: ensure healthy quorum before config update
  pkg/dnshelpers/util.go
  pkg/etcdcli/health.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/etcdenvvar/fake_envvar.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/control_plane_topology.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/operator/ceohelpers/qourum_check_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/testutils/testutils.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#928 [release-4.8] OCPBUGS-1307: backport owners
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low

#921 Bug 2046335: fix cert rotation on IP changes
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#923 Remove quorum guard pod after the pod is removed from the cluster
  pkg/operator/ceohelpers/common.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go
  pkg/operator/starter.go
Labels: approved, lgtm

#930 [release-4.8] OCPBUGS-1230: ensure healthy quorum before config update
  pkg/dnshelpers/util.go
  pkg/etcdcli/health.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/etcdenvvar/fake_envvar.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/control_plane_topology.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/operator/ceohelpers/qourum_check_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical

#932 OCPBUGS-1130: increase etcdGRPCRequestsSlow thresholds
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#924 OCPBUGS-685: preserve log message on failures
  pkg/etcdcli/health.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug
