Repository openshift/cluster-etcd-operator, pull requests merged in 2022-06, with the labels that each got.

#842 [release-4.10] Bug 2091604: Cherrypick create backup before each upgrade
  go.mod
  go.sum
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
  vendor/github.com/mcuadros/go-version/.gitignore
  vendor/github.com/mcuadros/go-version/.travis.yml
  vendor/github.com/mcuadros/go-version/LICENSE
  vendor/github.com/mcuadros/go-version/README.md
  vendor/github.com/mcuadros/go-version/compare.go
  vendor/github.com/mcuadros/go-version/constraint.go
  vendor/github.com/mcuadros/go-version/doc.go
  vendor/github.com/mcuadros/go-version/group.go
  vendor/github.com/mcuadros/go-version/normalize.go
  vendor/github.com/mcuadros/go-version/sort.go
  vendor/github.com/mcuadros/go-version/stability.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#845 Bug 2090929: cluster-backup.sh script has a conflict to use the '/etc/kubernetes/static-pod-certs' folder if a custom API certificate is defined
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#843 Bug 2092395: etcdHighNumberOfFailedGRPCRequests alerts with wrong results
  docs/HACKING.md
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/Makefile
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/README.md
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#851 Bug 2092880: avoid extrapolation in leaderhip alert
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#858 Bug 2095703: fix multi-address member removal
  pkg/operator/ceohelpers/common.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#862 Bug 2093819: add timeout to health checks
  pkg/etcdcli/health.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high
