Repository openshift/cluster-etcd-operator, pull requests merged in 2022-02, with the labels that each got.

#736 wait for other installers to finish
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm

#732 an e2e test for checking scaling up by one master node
  test/e2e/framework/clientset.go
  test/e2e/main_test.go
  test/e2e/vertical_scaling_test.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/doc.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machine.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/client-go/machine/clientset/versioned/typed/machine/v1beta1/machineset.go
  vendor/modules.txt
Labels: approved, lgtm

#743 Bug 2052270: pkg/operator/metriccontroller/fsync_controller: Fix "treshold" -> "thresholds" typos
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#741 changes the signature of the MemberRemove method to accept a memberID (uint64) not a Name (string)
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/helpers.go
  pkg/etcdcli/interfaces.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
Labels: approved, lgtm

#738 bug 2053148: [release-4.10] update library-go to get rapid installer pod fixes
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high, staff-eng-approved, backport-risk-assessed

#749 Bug 2053268: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/utils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backport-risk-assessed

#748 Bug 2053582: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/utils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#751 Bug 2053268: Track static pod lifecycle
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/missingstaticpod/missing_static_pod_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent, staff-eng-approved, backport-risk-assessed

#737 adds member removal controller
  pkg/etcdcli/helpers.go
  pkg/operator/ceohelpers/machine_api.go
  pkg/operator/ceohelpers/machine_api_test.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/machine/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/machine/informers/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/client-go/machine/informers/externalversions/machine/v1beta1/machine.go
  vendor/github.com/openshift/client-go/machine/informers/externalversions/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/client-go/machine/informers/externalversions/machine/v1beta1/machineset.go
  vendor/github.com/openshift/client-go/machine/listers/machine/v1beta1/expansion_generated.go
  vendor/github.com/openshift/client-go/machine/listers/machine/v1beta1/machine.go
  vendor/github.com/openshift/client-go/machine/listers/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/client-go/machine/listers/machine/v1beta1/machineset.go
  vendor/modules.txt
Labels: approved, lgtm

#740 an e2e test for checking scaling up and down by one master node
  test/e2e/main_test.go
  test/e2e/vertical_scaling_test.go
Labels: approved, lgtm

#754 Bug 2057644: Fix FSyncController degraded latch
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#756 Bug 2057642: Change fsync degraded reason to CamelCase
  pkg/operator/metriccontroller/fsync_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low
