Repository openshift/cluster-etcd-operator, pull requests merged in 2022-11, with the labels that each got.

#956 [4.10] OCPBUGS-2920: update prometheus alerts
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#961 OCPBUGS-2940: revisit defrag controller degradation
  pkg/etcdcli/helpers.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/defragcontroller/defragcontroller.go
  pkg/operator/defragcontroller/defragcontroller_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#963 add CEO overview slides
  docs/overview/images/CEO __ CEE.png
  docs/overview/images/CEO __ CEE_1.png
  docs/overview/images/CEO __ CEE_10.png
  docs/overview/images/CEO __ CEE_11.png
  docs/overview/images/CEO __ CEE_12.png
  docs/overview/images/CEO __ CEE_13.png
  docs/overview/images/CEO __ CEE_14.png
  docs/overview/images/CEO __ CEE_15.png
  docs/overview/images/CEO __ CEE_16.png
  docs/overview/images/CEO __ CEE_2.png
  docs/overview/images/CEO __ CEE_3.png
  docs/overview/images/CEO __ CEE_4.png
  docs/overview/images/CEO __ CEE_5.png
  docs/overview/images/CEO __ CEE_6.png
  docs/overview/images/CEO __ CEE_7.png
  docs/overview/images/CEO __ CEE_8.png
  docs/overview/images/CEO __ CEE_9.png
  docs/overview/overview_2022.md
Labels: approved, lgtm

#955 add test for bootstrap teardown controller
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm

#966 OCPBUGS-3929: update apf configuration to use v1beta2
  manifests/0000_20_etcd-operator_10_flowschema.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#935 certificate code cleanup
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm

#964 OCPBUGS-2852: later bootstrap removal in delayed scaling
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#967 OCPBUGS-4193: later bootstrap removal in delayed scaling
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug
