Repository openshift/cluster-etcd-operator, pull requests merged in 2022-10, with the labels that each got.

#938 OCPBUGS-1329: Add niceness to important etcd processes
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#917 Hypershift: Stop trying to apply etcd prometheusrule
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm

#937 OCPBUGS-1000: Allow scale-down of unhealthy member
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/etcdcli_test.go
  pkg/etcdcli/helpers.go
  pkg/etcdcli/interfaces.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#933 doc fixes for prometheus metrics
  docs/performance-metrics.md
Labels: approved, lgtm

#948 doc access clusterbot resources
  docs/access-clusterbot-resources.md
Labels: approved, lgtm

#950 library-go vendoring for installer cmd timeout
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#949 OCPBUGS-2577: fix cert rotation on IP changes
  .gitignore
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug

#958 [4.12] OCPBUGS-2918: update prometheus alerts
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#957 [4.11] OCPBUGS-2919: update prometheus alerts
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug

#947 ETCD-328: automatic replacement of an unhealthy member machine
  pkg/etcdcli/health.go
  pkg/etcdcli/health_test.go
  pkg/operator/ceohelpers/common.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Labels: approved, lgtm, tide/merge-method-squash
