Repository openshift/cluster-etcd-operator, pull requests merged in 2022-05, with the labels that each got.

#815 Bug 2077160: Adding Thomas to reviewers and me to approvers
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#814 test utils changes the way endpoints data key is calculated
  pkg/testutils/testutils.go
Labels: approved, lgtm

#802 manifests/deployment: comply to restricted pod security level
  manifests/0000_20_etcd-operator_06_deployment.yaml
Labels: approved, lgtm

#762 Bug 2063183: Upping defrag timeout to 1 minute
  pkg/etcdcli/etcdcli.go
  pkg/operator/defragcontroller/defragcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#760 Bug 2061496: Adding message to ControllerStarted:RecentBackup condition
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#817 Bug 2082312: Adding Thomas to reviewers, adding Allen to approvers
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#818 Bug 2082316: Add new etcd members to reviewers, add Allen to approvers
  OWNERS
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#822 Bug 2012065: Add summary to etcd alert rules
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#831 Updating cluster-etcd-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm, bugzilla/valid-bug

#823 Bug 2087983: remove etcd_perf before restore
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-low

#812 Bug 2073901: revisit defrag controller degradation
  pkg/etcdcli/helpers.go
  pkg/operator/defragcontroller/defragcontroller.go
  pkg/operator/defragcontroller/defragcontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#813 Bug 2085997: removes TestScalingUpAndDownSingleNode
  test/e2e/main_test.go
  test/e2e/vertical_scaling_test.go
  vendor/github.com/openshift/library-go/test/library/apiserver/apiserver.go
  vendor/github.com/openshift/library-go/test/library/client.go
  vendor/github.com/openshift/library-go/test/library/library.go
  vendor/github.com/openshift/library-go/test/library/pod_same_revision.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#826 [release-4.9] Bug 2086119: Add summary to etcd alert rules
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#838 Bug 2085997: increase initial delay seconds to match the discovery timeout
  bindata/etcd/pod.yaml
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#839 Bug 2085997: brings back initial delay seconds to the previous value
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#840 Bug 2085997: defines a startupProbe for etcd container
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
