Repository openshift/cluster-etcd-operator, pull requests merged in 2022-07, with the labels that each got.

#857 Bug 2097431: fix degraded missing cluster version
  pkg/operator/ceohelpers/common.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low

#868 Add documentation for profiling CEO
  docs/profiling_and_debugging.md
Labels: approved, lgtm

#869 Bug 1884568: Add etcd pod liveness probe
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#874 fixing unit test health flakes with tolerance
  pkg/cmd/monitor/monitor_test.go
Labels: approved, lgtm

#873 remove etcd-health-monitor sidecar from pod manifest
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#878 [release-4.10] Bug 2105148: fix degraded missing cluster version
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#828 [release-4.10] Bug 2086451: fix races in etcdclient
  .gitignore
  go.mod
  go.sum
  pkg/dnshelpers/util.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/etcdcli_pool.go
  pkg/etcdcli/etcdcli_pool_test.go
  pkg/etcdcli/etcdcli_test.go
  pkg/etcdcli/health.go
  pkg/etcdenvvar/etcd_env.go
  pkg/testutils/testutils.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#837 Bug 2089199: Move etcd monitoring dashboards CEO
  hack/generate.sh
  jsonnet/dashboard.jsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#883 fixing metrics proxy log spam
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm

#890 Bug 2097073: vendor upstream alerts
  jsonnet/jsonnetfile.lock.json
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#872 Bug 2061062: ensure healthy quorum before config update
  pkg/etcdcli/health.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/etcd_env.go
  pkg/etcdenvvar/fake_envvar.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/control_plane_topology.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/operator/ceohelpers/qourum_check_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, bugzilla/severity-urgent

#880 [release-4.10] Bug 2105249: Add etcd pod liveness and readiness probes
  bindata/etcd/pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/readyz/readyz.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#871 Exits with a non-zero code in case Etcd backup fails
  bindata/etcd/cluster-backup.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm
