Repository openshift/cluster-etcd-operator, pull requests merged in 2023-02, with the labels that each got.

#1002 fail early on missing node status envs
  go.mod
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/testutils/testutils.go
Labels: approved, lgtm

#1003 OCPBUGS-7374: set default timeouts in etcdcli
  pkg/cmd/verify/backupstorage.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/etcdcli_pool.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#968 OCPBUGS-4343: update apf configuration to use v1beta3
  manifests/0000_20_etcd-operator_10_flowschema.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1006 OCPBUGS-7510: [release-4.11] fail early on missing node status envs
  go.mod
  go.sum
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/testutils/testutils.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1009 OCPBUGS-7729: increase live/ready timeout and failure thresholds
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, jira/valid-bug, jira/valid-reference

#1010 [release-4.10] OCPBUGS-7827: set default timeouts in etcdcli
  pkg/cmd/verify/backupstorage.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/etcdcli_pool.go
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1012 ETCD-385: Prefer ipv6 on bootstrap in v6-primary dual stack
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
Labels: approved, lgtm, jira/valid-reference

#1013 document adaptation with ceo
  docs/etcd-tls-assets.md
Labels: approved, lgtm, ok-to-test
