Repository openshift/cluster-etcd-operator, pull requests merged in 2023-09, with the labels that each got.

#1105 OCPBUGS-18357: prepend authfile to podman create
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1111 OCPBUGS-18990: restore the correct static pod list
  bindata/etcd/cluster-restore.sh
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1109 ETCD-484: add e2e backup debug pod
  test/e2e/backup_script_test.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1110 indicate ownership of etcd certificates
  bindata/bootkube/manifests/etcd-client-secret.yaml
  bindata/bootkube/manifests/etcd-metric-client-secret.yaml
  bindata/bootkube/manifests/etcd-metric-serving-ca-configmap.yaml
  bindata/bootkube/manifests/etcd-metric-signer-secret.yaml
  bindata/bootkube/manifests/etcd-serving-ca-configmap.yaml
  bindata/bootkube/manifests/etcd-signer-secret.yaml
  go.mod
  go.sum
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  vendor/github.com/openshift/api/.gitignore
  vendor/github.com/openshift/api/Dockerfile.rhel8
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/annotations/annotations.go
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_azureprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/types_provider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.network.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#1113 OCPBUGS-19052: Avoid caching etcdctl on cluster-backup.sh
  bindata/etcd/etcd-common-tools
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#1122 [release-4.14] OCPBUGS-19553: Update static pod manifests perms
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1125 [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/stable.storage.testsuite.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_storage.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1126 OCPBUGS-19528: introduce backup removal controller
  bindata/etcd/backups-cr.yaml
  bindata/etcd/cluster-backup-cronjob.yaml
  pkg/cmd/request-backup/requestbackup.go
  pkg/operator/backupcontroller/backup_removal_controller.go
  pkg/operator/backupcontroller/backup_removal_controller_test.go
  pkg/operator/backupcontroller/backupcontroller.go
  pkg/operator/backupcontroller/backupcontroller_test.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/starter.go
  test/e2e/backup_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1119 ETCD-187: add dashboards CPU iotwait on master nodes
  jsonnet/cpu_iowait_dashboard.json
  jsonnet/dashboard.jsonnet
  manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
Labels: approved, lgtm, jira/valid-reference
