Repository openshift/cluster-etcd-operator, pull requests merged in 2023-03, with the labels that each got.

#1015 [release-4.9] OCPBUGS-7982: fail early on missing node status envs
  .gitignore
  go.mod
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/testutils/testutils.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1017 add resource removal by CVO
  docs/HACKING.md
Labels: approved, lgtm

#1022 [release-4.11] OCPBUGS-9908: Garbage collect grafana-dashboard-etcd
  hack/generate.sh
  jsonnet/jsonnetfile.lock.json
  jsonnet/removed_dashboard.jsonnet
  manifests/0000_90_cluster-etcd-operator_02-removed-dashboard.yaml
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1026 [release-4.10] OCPBUGS-10233: increase live/ready timeout and failure thresholds
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1030 OCPBUGS-10568: migrate to using lease objects for leader election
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1028 OCPBUGS-7785: migrate to using lease objects for leader election
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1027 OCPBUGS-10351: skip machine deletion during boostrap
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/ceohelpers/common_test.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/starter.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, cherry-pick-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1037 ETCD-410: Add Controller health to CEO liveness probe
  manifests/0000_20_etcd-operator_06_deployment.yaml
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/defragcontroller/defragcontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/health/aliveness_checker.go
  pkg/operator/health/aliveness_checker_test.go
  pkg/operator/health/checking_sync_wrapper.go
  pkg/operator/health/checking_sync_wrapper_test.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference
