Repository openshift/cluster-etcd-operator, pull requests merged in 2023-01, with the labels that each got.

#978 OCPBUGS-5304: should not scale-down when all members are healthy
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Labels: approved, lgtm

#980 ETCD-359: Remove quorum guard cleanup controller
  pkg/operator/quorumguardcleanup/quorumguardcleanupcontroller.go
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#990 pkg/operator/defragcontroller: Fix "stabalize" -> "stabilize" typo
  pkg/operator/defragcontroller/defragcontroller.go
Labels: approved, lgtm

#993 pkg/operator/etcdmemberscontroller: Slugify "No quorum" to "NoQuorum"
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
Labels: approved, lgtm

#992 OCPBUGS-5988: add dedicated success status for bootstrap removal
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
Labels: approved, lgtm, tide/merge-method-squash, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#972 [release-4.8] OCPBUGS-4775: only allow safe TLS1.2 and 1.3 ciphersuites in etcd and CEO
  bindata/etcd/pod.yaml
  pkg/cmd/readyz/readyz.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate
