Repository openshift/cluster-etcd-operator, pull requests merged in 2023-06, with the labels that each got.

#1059 OCPBUGS-14296: skip unstartedEtcdMember event
  pkg/operator/clustermembercontroller/clustermembercontroller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#1049 OCPBUGS-14255: Add Controller health to CEO liveness probe
  manifests/0000_20_etcd-operator_06_deployment.yaml
  pkg/cmd/operator/cmd.go
  pkg/operator/starter.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#1053 Remove unused cli docker image
  manifests/image-references
Labels: approved, lgtm, ok-to-test

#1060 manifests: bump loglevel of operator to normal
  manifests/0000_20_etcd-operator_06_deployment.yaml
Labels: approved, lgtm, ok-to-test
