Repository openshift/cluster-etcd-operator, pull requests merged in 2023-08, with the labels that each got.

#1083 OCPBUGS-16889: handle optional machineAPI
  pkg/operator/ceohelpers/machine_api.go
  pkg/operator/ceohelpers/machine_api_test.go
  pkg/operator/clustermembercontroller/clustermembercontroller.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1088 ETCD-448: add init container
  bindata/etcd/cluster-backup-cronjob.yaml
  pkg/cmd/prune-backups/prune.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller_test.go
Labels: approved, lgtm, jira/valid-reference

#1090 add backup pv pvc yaml
  hack/backup_pv_pvc.yaml
Labels: approved, lgtm

#1089 ETCD-460: add basic backup e2e tests
  bindata/etcd/backups-cr.yaml
  bindata/etcd/backups-crb.yaml
  bindata/etcd/backups-sa.yaml
  bindata/etcd/cluster-backup-cronjob.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go
  pkg/operator/starter.go
  test/e2e/backup_test.go
  test/e2e/framework/clients.go
  test/e2e/framework/clientset.go
Labels: approved, lgtm, jira/valid-reference

#1091 update overview slides
  docs/overview/images/CEO __ CEE_11_1.png
  docs/overview/images/CEO __ CEE_11_2.png
  docs/overview/images/CEO __ CEE_16.png
  docs/overview/images/CEO __ CEE_4.png
  docs/overview/images/CEO __ CEE_7.png
  docs/overview/images/CEO __ CEE_7_1.png
  docs/overview/overview.md
Labels: approved, lgtm

#1092 add processed label to skipped backups
  pkg/operator/backupcontroller/backupcontroller.go
  pkg/operator/backupcontroller/backupcontroller_test.go
Labels: approved, lgtm

#1094 OCPBUGS-16889: machine api check: rely on status more than baseline
  pkg/operator/ceohelpers/machine_api.go
  pkg/operator/ceohelpers/machine_api_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1093 e2e test for size retention
  pkg/cmd/prune-backups/prune.go
  pkg/cmd/prune-backups/prune_test.go
  test/e2e/backup_test.go
  test/e2e/etcdctl_test.go
Labels: approved, lgtm

#1095 add backup skip e2e test
  test/e2e/backup_test.go
Labels: approved, lgtm

#1096 add pvc validation and e2e tests
  pkg/operator/backupcontroller/backupcontroller.go
  pkg/operator/backupcontroller/backupcontroller_test.go
  test/e2e/backup_test.go
Labels: approved, lgtm

#1098 add e2e test for cronjob reconciliation failures
  test/e2e/backup_test.go
Labels: approved, lgtm

#1097 [release-4.14] OCPBUGS-18166: add etcd diskjitter dashboards
  jsonnet/dashboard.jsonnet
  jsonnet/diskjitter_dashboard.json
  manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-bug, jira/valid-reference
