Repository openshift/cluster-etcd-operator, pull requests merged in 2024-06, with the labels that each got.

#1265 [release-4.16] ETCD-621: Update api vendor libraries to get GA'ed tuning profiles
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-Default.crd.yaml
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1264 ETCD-620: Update api vendor libraries to get GA'ed tuning profiles
  go.mod
  go.sum
  vendor/github.com/openshift/api/Makefile
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/types_machineconfiguration.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_12_etcd_01_etcds-Default.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
  vendor/github.com/openshift/api/operator/v1/zz_generated.featuregated-crd-manifests.yaml
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1271 ETCD-606: Batch bundle revision rollout
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/cmd/operator/cmd.go
  pkg/cmd/render/certs_test.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, jira/valid-reference

#1195 NO-JIRA: Update etcd-tls-assets.md
  docs/etcd-tls-assets.md
Labels: lifecycle/rotten, approved, lgtm, jira/valid-reference

#1281 NO-JIRA: update library-go
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1283 NO-JIRA: fix false positive bootstrap in cert signer controller
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, lgtm, jira/valid-reference
