Repository openshift/cluster-etcd-operator, pull requests merged in 2024-07, with the labels that each got.

#1285 NO-JIRA: cert rotation same assertions
  pkg/cmd/render/certs_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, jira/valid-reference

#1286 OCPBUGS-36301: parallelize member health checks
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/health.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1288 NO-JIRA: only read signer/bundles on forced leaf generation
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, jira/valid-reference

#1293 OCPBUGS-36621: add etcd-all-bundles to cvo create-only
  manifests/0000_20_etcd-operator_03_configmap.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1294 ETCD-574: Update TLS artifact descriptions according to registry requ…
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, jira/valid-reference

#1295 Revert "OCPBUGS-36621: add etcd-all-bundles to cvo create-only"
  manifests/0000_20_etcd-operator_03_configmap.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1296 OCPBUGS-36621: Force sync on missing etcd-all-bundles configmap
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1292 ETCD-604: Prune revisioned resources
  docs/etcd-tls-assets.md
  pkg/cmd/render/certs_test.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1297 ETCD-636: expose PruneOpts
  pkg/cmd/prune-backups/prune.go
  pkg/cmd/prune-backups/prune_test.go
Labels: approved, lgtm, jira/valid-reference

#1300 NO-JIRA: only update envvar listeners on real changes
  pkg/etcdenvvar/envvarcontroller.go
Labels: approved, lgtm, jira/valid-reference
