Repository openshift/cluster-etcd-operator, pull requests merged in 2024-03, with the labels that each got.

#1215 OCPBUGS-30169: add timeout to etcd client.New config
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/etcdcli_opts.go
Labels: approved, lgtm, cherry-pick-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1208 ETCD-349: add etcd cachedmembers
  pkg/etcdcli/cached_members.go
  pkg/etcdcli/cached_members_test.go
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/health.go
  pkg/etcdcli/interfaces.go
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/qourum_check.go
  pkg/operator/defragcontroller/defragcontroller.go
  pkg/operator/defragcontroller/defragcontroller_test.go
  pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
  pkg/operator/starter.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1219 WRKLDS-1071: bump(library-go)=master
  go.mod
  go.sum
  pkg/tlshelpers/tlshelpers.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1216 OCPBUGS-30245: [4.13] Replace nodelister with master nodelister everywhere
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1223 OCPBUGS-30873: CEO aliveness check should only detect deadlocks
  pkg/operator/health/aliveness_checker.go
  pkg/operator/health/checking_sync_wrapper.go
  pkg/operator/health/checking_sync_wrapper_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1222 Revert "OCPBUGS-30169: add timeout to etcd client.New config"
  pkg/etcdcli/etcdcli.go
  pkg/etcdcli/etcdcli_opts.go
Labels: approved, lgtm, cherry-pick-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1200 ETCD-535: Manual CA rotation should rotate all leaf certs
  go.mod
  go.sum
  pkg/tlshelpers/target_cert_creator.go
  pkg/tlshelpers/target_cert_creator_test.go
  pkg/tlshelpers/tlshelpers.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only
