Repository openshift/cluster-etcd-operator, pull requests merged in 2024-09, with the labels that each got.

#1304 ETCD-659: Add `etcd-backup-server` sidecar skeleton
  bindata/etcd/pod.yaml
  cmd/cluster-etcd-operator/main.go
  pkg/cmd/backuprestore/backupserver.go
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1313 ETCD-654: start with quorum restore script
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  bindata/etcd/quorum-restore-pod.yaml
  bindata/etcd/quorum-restore.sh
  bindata/etcd/scripts-cm.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, jira/valid-reference

#1305 ETCD-660: Add `etcd-backup-server` backup vars
  bindata/etcd/pod.yaml
  pkg/backuphelpers/backupvars.go
  pkg/backuphelpers/backupvars_test.go
  pkg/cmd/backuprestore/backupserver.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1306 ETCD-661: Add `etcd-backup-server` scheduling logic
  bindata/etcd/pod.yaml
  go.mod
  go.sum
  pkg/cmd/backuprestore/backupserver.go
  pkg/cmd/backuprestore/backupserver_test.go
  pkg/operator/etcd_assets/bindata.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1333 NO-JIRA: fix log folder permission
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, jira/valid-reference

#1334 ETCD-666: Add etcd-backup-server pruning logic
  pkg/cmd/backuprestore/backupserver.go
  pkg/cmd/backuprestore/backupserver_test.go
  pkg/cmd/prune-backups/prune.go
  pkg/cmd/prune-backups/prune_test.go
Labels: approved, lgtm, jira/valid-reference

#1337 ETCD-656: add cluster identifier to revision.json
  pkg/cmd/rev/rev.go
  pkg/cmd/rev/rev_test.go
Labels: approved, lgtm, jira/valid-reference

#1338 create CRDs from openshift/api
  Dockerfile.ocp
Labels: approved

#1341 ETCD-662: fix: etcd-backup-server prune path
  pkg/cmd/backuprestore/backupserver.go
Labels: approved, lgtm, jira/valid-reference

#1330 ETCD-653: Update restore-pod to use locally stored revision
  bindata/etcd/cluster-restore.sh
  bindata/etcd/etcd-common-tools
  bindata/etcd/restore-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, jira/valid-reference
