Repository openshift/cluster-etcd-operator, pull requests merged in 2024-02, with the labels that each got.

#1177 ETCD-512: refactoring the cert signer controller
  docs/etcd-tls-assets.md
  go.mod
  go.sum
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/tlshelpers/tlshelpers.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1193 TRT-1485: Revert #1177 "ETCD-512: refactoring the cert signer controller"
  docs/etcd-tls-assets.md
  go.mod
  go.sum
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/tlshelpers/tlshelpers.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1198 AUTH-481: Add PSa labels to openshift-etcd-operator namespace
  manifests/0000_20_etcd-operator_00_namespace.yaml
Labels: approved, lgtm, jira/valid-reference

#1194 ETCD-512: refactoring the cert signer controller
  docs/etcd-tls-assets.md
  go.mod
  go.sum
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/tlshelpers/tlshelpers.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1199 Revert "Revert "OCPBUGS-22969: Use v1 for flowcontrol API""
  manifests/0000_20_etcd-operator_10_flowschema.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1189 OCPBUGS-27926: Updating cluster-etcd-operator-container image to be c…
  .ci-operator.yaml
  Dockerfile.rhel7
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1203 NO-JIRA: increase client pool size
  pkg/etcdcli/etcdcli_pool.go
Labels: approved, lgtm, jira/valid-reference

#1202 ETCD-516: CEO needs to react on changing CA cert bundle and client certs
  manifests/0000_20_etcd-operator_06_deployment.yaml
Labels: approved, lgtm, jira/valid-reference

#1186 ETCD-517: run certsignercontroller for bootstrap render
  bindata/bootkube/manifests/etcd-ca-bundle-configmap.yaml
  bindata/bootkube/manifests/etcd-client-secret.yaml
  bindata/bootkube/manifests/etcd-metric-client-secret.yaml
  bindata/bootkube/manifests/etcd-metric-serving-ca-configmap.yaml
  bindata/bootkube/manifests/etcd-metric-signer-secret.yaml
  bindata/bootkube/manifests/etcd-serving-ca-configmap.yaml
  bindata/bootkube/manifests/etcd-signer-secret.yaml
  go.mod
  pkg/cmd/render/certs.go
  pkg/cmd/render/certs_test.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/resourcesynccontroller/resourcesynccontroller.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, jira/valid-reference

#1205 NO-JIRA: replace nodelister with master nodelister
  pkg/cmd/render/certs.go
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, jira/valid-reference

#1206 OCPBUGS-29717: [4.15] Replace nodelister with master nodelister everywhere
  pkg/etcdenvvar/envvarcontroller.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
