Repository openshift/cluster-etcd-operator, pull requests merged in 2024-10, with the labels that each got.

#1346 ETCD-678: introduce a templated pod.yaml
  bindata/etcd/pod.gotpl.yaml
  pkg/backuphelpers/backupvars.go
  pkg/backuphelpers/backupvars_test.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Labels: approved, lgtm, jira/valid-reference

#1345 ETCD-679: Add etcd backup server container failure resolution
  pkg/backuphelpers/backupvars.go
  pkg/cmd/backuprestore/backupserver.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1350 OCPBUGS-17199: remove stability check from bootstrap completeness
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1358 ETCD-686: Remove etcd-backup-server StaticPod approach
  bindata/etcd/pod.gotpl.yaml
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/testutils/testutils.go
Labels: approved, lgtm, jira/valid-reference

#1357 OCPBUGS-17199: Revert pull request https://github.com/openshift/cluster-etcd-operator/issues/1350
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1361 OCPBUGS-43920: operator: remove duplicate kube client
  pkg/operator/starter.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1365 NO-JIRA: bump library-go
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/test_operator_client.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
