Repository openshift/cluster-etcd-operator, pull requests merged in 2024-04, with the labels that each got.

#1226 NO-JIRA: fail certsignercontroller sync when secret can not be applied
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Labels: approved, lgtm, jira/valid-reference

#1238 ETCD-580: Decrease validity period to prevent cert expiry for offline clusters
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, jira/valid-reference

#1235 ETCD-579: store revision at which signers are rotated
  go.mod
  go.sum
  pkg/cmd/render/certs.go
  pkg/cmd/render/certs_test.go
  pkg/operator/ceohelpers/common.go
  pkg/operator/ceohelpers/common_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/testutils/testutils.go
  pkg/tlshelpers/client_lister.go
  pkg/tlshelpers/client_lister_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1243 Revert "ETCD-579: store revision at which signers are rotated"
  go.mod
  go.sum
  pkg/cmd/render/certs.go
  pkg/cmd/render/certs_test.go
  pkg/operator/ceohelpers/common.go
  pkg/operator/ceohelpers/common_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/testutils/testutils.go
  pkg/tlshelpers/client_lister.go
  pkg/tlshelpers/client_lister_test.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1245 OCPBUGS-32176: immediately return on dynamic certs errors
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1244 NO-ISSUE: use IsBootstrapComplete from library-go
  pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
  pkg/operator/ceohelpers/bootstrap.go
  vendor/github.com/openshift/library-go/pkg/operator/bootstrap/bootstrap.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1247 API-1800: manifests: convert SecretTypeTLS secrets to kubernetes.io/tls
  manifests/0000_20_etcd-operator_03_secret.yaml
Labels: approved, lgtm, jira/valid-reference

#1249 ETCD-583: add signer expiration metric and alert
  jsonnet/custom.libsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
  pkg/cmd/render/certs.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
Labels: approved, lgtm, jira/valid-reference

#1230 OCPBUGS-31249: remove etcd-health-probe log
  bindata/etcd/pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/valid-reference

#1182 NO-JIRA: remove cluster-backup pod
  bindata/etcd/cluster-backup-pod.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference
