Repository openshift/cluster-etcd-operator, pull requests merged in 2024-11, with the labels that each got.

#1360 OCPBUGS-17199: Separated the revision stability check from the bootstrap completeness check
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1371 API-1835: bump library-go
  go.mod
  go.sum
  pkg/cmd/operator/cmd.go
  pkg/cmd/render/certs.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/operator/clustermembercontroller/clustermembercontroller_test.go
  pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
  pkg/operator/defragcontroller/defragcontroller_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
  pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
  pkg/tlshelpers/target_cert_creator_test.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
  vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1364 OCPBUGS-43748: etcd pod containers do not start when tls min version is 1.3
  bindata/etcd/pod.gotpl.yaml
  pkg/cmd/readyz/readyz.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, cherry-pick-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
