Repository openshift/cluster-etcd-operator, pull requests merged in 2024-05, with the labels that each got.

#1239 OCPBUGS-31849: check the quorum in case the cluster is healthy or not after generating certs
  pkg/operator/ceohelpers/bootstrap.go
  pkg/operator/ceohelpers/bootstrap_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#1260 OCPBUGS-33495: return errors in wait-for-ceo
  pkg/cmd/waitforceo/waitforceo.go
  pkg/operator/bootstrapteardown/waitforceo.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1262 NO-JIRA:check the cluster is healthy or not after getting env var, to ensure it is safe to rollout
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#1267 ETCD-603: add revision helpers
  pkg/operator/ceohelpers/common.go
  pkg/operator/ceohelpers/common_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Labels: approved, lgtm, jira/valid-reference

#1268 ETCD-606: Batch bundle revision rollout
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/cmd/render/certs_test.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1270 TRT-1687: Revert #1268 "ETCD-606: Batch bundle revision rollout"
  bindata/etcd/pod.yaml
  bindata/etcd/restore-pod.yaml
  pkg/cmd/render/certs_test.go
  pkg/etcdenvvar/envvarcontroller_test.go
  pkg/etcdenvvar/etcd_env.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/tlshelpers/tlshelpers.go
Labels: approved, lgtm, jira/valid-reference
