Repository openshift/cluster-etcd-operator, pull requests merged in 2025-07, with the labels that each got.

#1431 OCPBUGS-57372: Wait for 2 cp nodes before starting TNF jobs
  pkg/tnf/operator/starter.go
  pkg/tnf/pkg/config/cluster.go
  pkg/tnf/pkg/config/cluster_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1439 OCPBUGS-58294: Use 1 pod manifest only, set fields dynamically, deduplicate job creation
  bindata/tnfdeployment/authjob.yaml
  bindata/tnfdeployment/fencingjob.yaml
  bindata/tnfdeployment/job.yaml
  bindata/tnfdeployment/setupjob.yaml
  cmd/tnf-setup-runner/main.go
  pkg/tnf/after-setup/runner.go
  pkg/tnf/assets/bindata.go
  pkg/tnf/fencing/runner.go
  pkg/tnf/operator/starter.go
  pkg/tnf/pkg/tools/jobs.go
  pkg/tnf/pkg/tools/jobtimeouts.go
  pkg/tnf/setup/runner.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1444 OCPBUGS-50488: add missing ports to svc and pod spec
  bindata/etcd/pod.gotpl.yaml
  bindata/etcd/svc.yaml
  pkg/operator/etcd_assets/bindata.go
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/valid-reference

#1445 NO-JIRA: Migrate bindata to go:embed
  Makefile
  bindata/assets.go
  bindata/etcd/pod.yaml
  go.mod
  go.sum
  pkg/dependencymagnet/doc.go
  pkg/operator/backupcontroller/backupcontroller.go
  pkg/operator/ceohelpers/podsubstitution.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/externaletcdsupportcontroller/external_etcd_support_controller.go
  pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go
  pkg/operator/scriptcontroller/scriptcontroller.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
  pkg/tnf/assets/bindata.go
  pkg/tnf/operator/starter.go
  vendor/github.com/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/_config.yml
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/file.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/toc.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference, acknowledge-critical-fixes-only

#1425 CNTRLPLANE-949: Add readonlyRootFilesystem
  bindata/etcd/pod.gotpl.yaml
  manifests/0000_20_etcd-operator_06_deployment.yaml
  test/e2e/etcdctl_test.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference
