Repository openshift/cluster-etcd-operator, pull requests merged in 2025-04, with the labels that each got.

#1399 OCPEDGE-1498: support updates to external etcd
  bindata/etcd/external-etcd-pod-cm.yaml
  pkg/dualreplicahelpers/dual_replica_helpers.go
  pkg/dualreplicahelpers/dual_replica_helpers_test.go
  pkg/operator/ceohelpers/control_plane_topology.go
  pkg/operator/ceohelpers/podsubstitution.go
  pkg/operator/ceohelpers/unsupported_override.go
  pkg/operator/ceohelpers/unsupported_override_test.go
  pkg/operator/etcd_assets/bindata.go
  pkg/operator/externaletcdsupportcontroller/external_etcd_support_controller.go
  pkg/operator/externaletcdsupportcontroller/external_etcd_support_controller_test.go
  pkg/operator/starter.go
  pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Labels: approved, lgtm, jira/valid-reference

#1402 OCPBUGS-54222: increase etcdGRPCRequestsSlow duration
  jsonnet/custom.libsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, cherry-pick-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#1400 OCPEDGE-1495: Update CEO to run pacemaker initialization commands
  .gitignore
  Dockerfile.ocp
  Makefile
  OWNERS_ALIASES
  bindata/tnfdeployment/OWNERS
  bindata/tnfdeployment/aftersetupjob.yaml
  bindata/tnfdeployment/authjob.yaml
  bindata/tnfdeployment/clusterrole-binding.yaml
  bindata/tnfdeployment/clusterrole.yaml
  bindata/tnfdeployment/role-binding.yaml
  bindata/tnfdeployment/role.yaml
  bindata/tnfdeployment/sa.yaml
  bindata/tnfdeployment/setupjob.yaml
  cmd/tnf-setup-runner/OWNERS
  cmd/tnf-setup-runner/main.go
  pkg/operator/starter.go
  pkg/tnf/OWNERS
  pkg/tnf/after-setup/runner.go
  pkg/tnf/assets/bindata.go
  pkg/tnf/auth/runner.go
  pkg/tnf/operator/dualreplicahelpers/dual_replica_helpers.go
  pkg/tnf/operator/dualreplicahelpers/dual_replica_helpers_test.go
  pkg/tnf/operator/starter.go
  pkg/tnf/operator/starter_test.go
  pkg/tnf/pkg/config/cluster.go
  pkg/tnf/pkg/config/cluster_test.go
  pkg/tnf/pkg/etcd/etcd.go
  pkg/tnf/pkg/etcd/etcd_test.go
  pkg/tnf/pkg/exec/exec.go
  pkg/tnf/pkg/jobs/batch.go
  pkg/tnf/pkg/jobs/jobcontroller.go
  pkg/tnf/pkg/jobs/jobcontroller_test.go
  pkg/tnf/pkg/pcs/cluster.go
  pkg/tnf/pkg/pcs/etcd.go
  pkg/tnf/pkg/tools/conditions.go
  pkg/tnf/pkg/tools/json.go
  pkg/tnf/setup/runner.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#1412 OCPBUGS-53512: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#1413 OCPBUGS-53513: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1414 OCPBUGS-53511: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1403 OCPBUGS-53510: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1404 OCPBUGS-53506: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1405 OCPBUGS-53507: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1409 OCPEDGE-1773: Fix arbiter field in install-config
  pkg/operator/configobservation/controlplanereplicascount/observe_control_plane_replicas_count.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference
