Repository openshift/cluster-etcd-operator, pull requests merged in 2025-05, with the labels that each got.

#1417 OCPBUGS-55111: Remove 'meta' keyword from pcs resource create command
  pkg/tnf/pkg/pcs/etcd.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1416 OCPBUGS-53508: fix CVE-2025-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/modules.txt
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#1422 OCPBUGS-55757: adjust alerts according to platform
  jsonnet/custom.libsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1315 CNTRLPLANE-340: Issue shorter certs when ShortCertRotation feature gate is set
  go.mod
  go.sum
  pkg/cmd/render/certs.go
  pkg/cmd/render/certs_test.go
  pkg/cmd/render/render.go
  pkg/cmd/render/render_test.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
  pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
  pkg/operator/starter.go
  pkg/tlshelpers/tlshelpers.go
  vendor/github.com/evanphx/json-patch/.gitignore
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/openshift/api/features.md
  vendor/github.com/openshift/api/features/features.go
  vendor/github.com/openshift/api/features/legacyfeaturegates.go
  vendor/github.com/openshift/api/features/util.go
  vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/json_patch_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiregistration.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference
