Repository openshift/cluster-etcd-operator, pull requests merged in 2025-08, with the labels that each got.

#1463 OCPEDGE-1998: TNF: Use `pcmk_delay_base` on 1st fence device to prevent fencing races
  pkg/tnf/pkg/pcs/fencing.go
  pkg/tnf/pkg/pcs/fencing_test.go
Labels: approved, lgtm, jira/valid-reference

#1459 NO-JIRA: Add more unit tests for JobController
  pkg/tnf/pkg/jobs/jobcontroller_test.go
Labels: approved, lgtm, jira/valid-reference

#1469 OCPBUGS-60547: Revert "Vendor latest mixin, including additional and modified alerts for `etcdDatabaseQuotaLowSpace`"
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/alerts/alerts.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  jsonnet/vendor/github.com/jsonnet-libs/xtd/ascii.libsonnet
  jsonnet/vendor/github.com/jsonnet-libs/xtd/docs/ascii.md
  jsonnet/vendor/github.com/jsonnet-libs/xtd/docs/inspect.md
  jsonnet/vendor/github.com/jsonnet-libs/xtd/inspect.libsonnet
  jsonnet/vendor/github.com/jsonnet-libs/xtd/test/inspect_test.jsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1471 OCPBUGS-60237: Vendor latest mixin, including additional and modified alerts for etcdDatabaseQuotaLowSpace
  jsonnet/custom.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/alerts/alerts.libsonnet
  jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml
  jsonnet/vendor/github.com/jsonnet-libs/xtd/ascii.libsonnet
  jsonnet/vendor/github.com/jsonnet-libs/xtd/docs/ascii.md
  jsonnet/vendor/github.com/jsonnet-libs/xtd/docs/inspect.md
  jsonnet/vendor/github.com/jsonnet-libs/xtd/inspect.libsonnet
  jsonnet/vendor/github.com/jsonnet-libs/xtd/test/inspect_test.jsonnet
  manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#1474 OCPBUGS-60941: add individual context to the health check
  pkg/etcdcli/health.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
